#adição "+"
#subtração "-"
#multiplicação "*"
#divisão "/"
#potencia "**", "pow(base, potencia)"
#raiz quadrada "raiz**(1/2)"
#raiz cubica "raiz**(1/3)"
#divisão inteira "//"
#resto da divisão "%"
#ordem de precedência:
#1: "()"
#2: "**"
#3: "*", "/", "//", "%"
#4: "+", "-"